import React from "react";

export const Drinks = () => {
    return(
        <div>
            <div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div><div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div>
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks
            drinks  
        </div>
    )
}